#!/bin/bash

#Colors_BEGIN

clear
red='\e[0;31m'
green='\e[1;32m'
orange='\e[1;33m'
lightblue='\e[0;34m'
purple='\e[0;35m'
cyan='\e[0;36m'
lightgray='\e[0;37m'
darkgray='\e[1;30em'
lightred='\e[1;31m'
lightgreen='\e[0;32m'
yellow='\e[0;49;93m'
blue='\e[1;34m'
lightpurple='\e[1;35m'
lightcyan='\e[1;36m'
white='\e[1;37m'
nc="\e[0m"

#Colors_END

#echo "Do you want to install it? (Y/n)" 
read -p "Do you want to install it? [Y/n] " answ1
clear
sleep 0.5
if  [ "$answ1" = "y" ] || [ "$answ1" = "Y" ]; then
while true;
	do
	echo "copying file to /usr/bin"
	sleep 0.1
	clear
	echo "copying file to /usr/bin."
	sleep 0.1
	clear
	echo "copying file to /usr/bin.."
	sleep 0.1
	clear
	echo "copying file to /usr/bin..."
	sleep 0.1
	clear
done &

trap 'kill $!' SIGTERM SIGKILL
sleep 1
cp netTool.sh /usr/bin
mv /usr/bin/netTool.sh /usr/bin/netTool
sleep 0.5
 kill $!
	 echo "DONE"
	 sleep 0.5
	 echo "Now you can run"" 'netTool' ""from anywhere in the Terminal "
	 chmod +x update
	 chmod +x install 
	 chmod +x netTool.sh
	 chmod +x /usr/bin/netTool
	 sleep 2

 #echo "Do you want to run it? (Y/n)"
 read -p "Do you want to run it? [Y/n] " answ2

 if [[ "$answ2" = "y" ]] || [[ "$answ2" = "Y" ]]  ; then
 	bash netTool
 else

 	echo "Aboarding..."
		exit 1

 fi
	else
		echo "Aboarding..."
		exit 1
fi
