#!/bin/bash
#Colors_BEGIN

clear
red='\e[0;31m'
green='\e[1;32m'
orange='\e[1;33m'
lightblue='\e[0;34m'
purple='\e[0;35m'
cyan='\e[0;36m'
lightgray='\e[0;37m'
darkgray='\e[1;30em'
lightred='\e[1;31m'
lightgreen='\e[0;32m'
yellow='\e[0;49;93m'
blue='\e[1;34m'
lightpurple='\e[1;35m'
lightcyan='\e[1;36m'
white='\e[1;37m'
nc="\e[0m"

#Colors_END

#checking for internet
while true; do
echo -e "$yellow""Checking for internet connection$nc"
sleep 0.1
clear
echo -e "$yellow""Checking for internet connection.$nc"
sleep 0.1
clear
echo -e "$yellow""Checking for internet connection..$nc"
sleep 0.1
clear
echo -e "$yellow""Checking for internet connection...$nc"
sleep 0.1
clear

done & 
trap 'kill $!' SIGTERM SIGKILL
sleep 2
wget -q --spider https://www.google.com
if [ $? -eq 0 ]; then
    echo -e "$green""Connected to internet$nc [$green✓$nc]"
    kill $!
    sleep 3
    clear
    sleep 0.5
# Updating netTool
    while true; do
    echo -e $blue"Updating NetTool from Github"
    sleep 0.1
    clear
    echo -e $blue"Updating NetTool from Github."
    sleep 0.1
    clear
    echo -e $blue"Updating NetTool from Github.."
    sleep 0.1
    clear
    echo -e $blue"Updating NetTool from Github..."
    sleep 0.1
    clear 
    done &
    trap 'kill $!' SIGTERM SIGKILL
    sleep 1
    netTool_path=$(find $HOME/ -name "netTool" | grep /NetTool/netTool)
    NetTool_path=$(find $HOME/ -name "NetTool" | grep /NetTool)
    cd >/dev/null 2>&1
    cd $NetTool_path >/dev/null 2>&1
    git reset HEAD --hard >/dev/null 2>&1
    git pull origin master >/dev/null 2>&1
    rm /usr/bin/netTool
    cp $netTool_path /usr/bin
    sleep 1
    echo -e $green"Update success!" 
    kill $!
    sleep 0.5
    echo -e $yellow"Applying Execution Permissions to netTool..."
    sleep 0.5
    chmod +x netTool >/dev/null 2>&1
    chmod +x /usr/bin/netTool 2>&1
    chmod +x update >/dev/null 2>&1
    chmod +x install >/dev/null 2>&1
    sleep 0.5
    echo -e $blue"DONE"
    kill $!
    sleep 1
    read -p "Rerun netTool? [Y/n] " anssw
    if  [ "$anssw" = "y" ] || [ "$answ1" = "Y" ]; then
    sleep 0.5
    netTool
    else
    echo "Aboarding..."
    exit 1
    
else   
    echo -e "$lightred""No internet connection$nc [$ligthred✗$nc]$nc"
    echo -e "$yellow""Please make sure you are connected to internet!" "$nc"
    kill $!
    exit 1
fi
